global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Java Spring Boot Server
  - job_name: 'grpc-server'
    static_configs:
      - targets: ['grpc-server:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s

  # Java Spring Boot Server gRPC port (removed - gRPC doesn't expose HTTP metrics)
  # - job_name: 'grpc-server-grpc'
  #   static_configs:
  #     - targets: ['grpc-server:9090']
  #   metrics_path: '/actuator/prometheus'
  #   scrape_interval: 3s

  # Node.js Client API
  - job_name: 'grpc-client'
    static_configs:
      - targets: ['grpc-client:3000']
    metrics_path: '/metrics'
    scrape_interval: 3s

  # Java High-Performance Client
  - job_name: 'grpc-java-client'
    static_configs:
      - targets: ['grpc-java-client:3001']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
